backend:
  name: git-gateway
  branch: master

media_folder: static/img
public_folder: /img

collections:
  - name: "press"
    label: "Press"
    folder: "src/pages/press"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "press-post"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Tags", name: "tags", widget: "list"}

  - name: "initiative"
    label: "Initiatives"
    create: true
    files:
      - file: "src/pages/initiatives/philosophy-of-love.md"
        label: "Philosophy of Love"
        name: "philosophy-of-love"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "initiative-page"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Body", name: "body", widget: "markdown"}
      - file: "src/pages/initiatives/coders-beyond-bars.md"
        label: "Coders Beyond Bars"
        name: "coders-beyond-bars"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "initiative-page"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Body", name: "body", widget: "markdown"}

  - name: "resources"
    label: "Resources"
    files:
      - file: "src/pages/resources/index.md"
        label: "Resources"
        name: "resources"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "resources-page"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Body", name: "body", widget: "markdown"}
